# Generated by Django 4.2.1 on 2023-05-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('options', models.JSONField()),
                ('rightAnswer', models.IntegerField(blank=True, null=True)),
                ('startDate', models.DateTimeField(blank=True, null=True)),
                ('endDate', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'active'), ('inactive', 'inactive'), ('finished', 'finished')], max_length=25, null=True)),
            ],
            options={
                'db_table': 'quiz_creation',
            },
        ),
    ]
